[project]
name = "tap-moonnox-jira"
version = "0.1.0"
requires-python = ">=3.11, <4.0"
dependencies = [
  "singer-python==6.1.1",
  "requests~=2.32.4"
]

[tool.optional-dependencies]
dev = [
  "pylint>=3.3.7",
  "black>=25.1.0"
]

[project.scripts]
tap-jira = "tap_jira.cli:run"

[tool.black]
line-length = 79

[build-system]
requires = ["setuptools>=80", "wheel"]
build-backend = "setuptools.build_meta"
